=== Rolk254/nsla/xm_xs/calendar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="temporada1">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="jornada" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="partido" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="fecha" type="xs:string" />
                                        <xs:element name="hora" type="xs:string" />
                                        <xs:element name="equipos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="local" type="xs:string" />
                                                    <xs:element name="visitante" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="num" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Rolk254/nsla/xm_xs/calendar.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="calendar.xsl"?>
<temporada1 xsi:noNamespaceSchemaLocation="calendar.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <jornada num="1">
        <partido>
            <fecha>Viernes, 13 de octubre</fecha>
            <hora>20:00</hora>
            <equipos>
                <local>Cardinals</local>
                <visitante>Cowboys</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Sábado, 14 de octubre</fecha>
            <hora>21:30</hora>
            <equipos>
                <local>Raiders</local>
                <visitante>Steelers</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Domingo, 15 de octubre</fecha>
            <hora>23:00</hora>
            <equipos>
                <local>Bengals</local>
                <visitante>Rams</visitante>
            </equipos>
        </partido>
    </jornada>
    <jornada num="2">
        <partido>
            <fecha>Viernes, 20 de octubre</fecha>
            <hora>19:00</hora>
            <equipos>
                <local>Cowboys</local>
                <visitante>Cardinals</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Sábado, 21 de octubre</fecha>
            <hora>21:00</hora>
            <equipos>
                <local>Steelers</local>
                <visitante>Raiders</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Domingo, 22 de octubre</fecha>
            <hora>18:00</hora>
            <equipos>
                <local>Rams</local>
                <visitante>Bengals</visitante>
            </equipos>
        </partido>
    </jornada>
    <jornada num="3">
        <partido>
            <fecha>Martes, 24 de octubre</fecha>
            <hora>16:30</hora>
            <equipos>
                <local>Cardinals</local>
                <visitante>Raiders</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 25 de octubre</fecha>
            <hora>18:00</hora>
            <equipos>
                <local>Cowboys</local>
                <visitante>Bengals</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 26 de octubre</fecha>
            <hora>20:00</hora>
            <equipos>
                <local>Rams</local>
                <visitante>Steelers</visitante>
            </equipos>
        </partido>
    </jornada>
    <jornada num="4">
        <partido>
            <fecha>Martes, 7 de noviembre</fecha>
            <hora>17:15</hora>
            <equipos>
                <local>Raiders</local>
                <visitante>Cardinals</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 8 de noviembre</fecha>
            <hora>18:45</hora>
            <equipos>
                <local>Bengals</local>
                <visitante>Cowboys</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 9 de noviembre</fecha>
            <hora>20:30</hora>
            <equipos>
                <local>Steelers</local>
                <visitante>Rams</visitante>
            </equipos>
        </partido>
    </jornada>
    <jornada num="5">
        <partido>
            <fecha>Lunes, 20 de noviembre</fecha>
            <hora>16:45</hora>
            <equipos>
                <local>Rams</local>
                <visitante>Steelers</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Martes, 21 de noviembre</fecha>
            <hora>18:15</hora>
            <equipos>
                <local>Bengals</local>
                <visitante>Cardinals</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 22 de noviembre</fecha>
            <hora>19:45</hora>
            <equipos>
                <local>Chiefs</local>
                <visitante>Bears</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 23 de noviembre</fecha>
            <hora>21:15</hora>
            <equipos>
                <local>Cowboys</local>
                <visitante>Raiders</visitante>
            </equipos>
        </partido>
    </jornada>
    <jornada num="6">
        <partido>
            <fecha>Lunes, 4 de diciembre</fecha>
            <hora>16:45</hora>
            <equipos>
                <local>Steelers</local>
                <visitante>Rams</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Martes, 5 de diciembre</fecha>
            <hora>18:15</hora>
            <equipos>
                <local>Cardinals</local>
                <visitante>Bengals</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 6 de diciembre</fecha>
            <hora>19:45</hora>
            <equipos>
                <local>Bears</local>
                <visitante>Chiefs</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 7 de diciembre</fecha>
            <hora>21:15</hora>
            <equipos>
                <local>Raiders</local>
                <visitante>Cowboys</visitante>
            </equipos>
        </partido>
    </jornada>
    <jornada num="7">
        <partido>
            <fecha>Lunes, 11 de diciembre</fecha>
            <hora>16:30</hora>
            <equipos>
                <local>Cowboys</local>
                <visitante>Rams</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Martes, 12 de diciembre</fecha>
            <hora>18:00</hora>
            <equipos>
                <local>Raiders</local>
                <visitante>Cardinals</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 13 de diciembre</fecha>
            <hora>19:30</hora>
            <equipos>
                <local>Bengals</local>
                <visitante>Bears</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 14 de diciembre</fecha>
            <hora>21:00</hora>
            <equipos>
                <local>Chiefs</local>
                <visitante>Steelers</visitante>
            </equipos>
        </partido>
    </jornada> 
    <jornada num="8">
        <partido>
            <fecha>Lunes, 18 de diciembre</fecha>
            <hora>16:30</hora>
            <equipos>
                <local>Rams</local>
                <visitante>Cowboys</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Martes, 19 de diciembre</fecha>
            <hora>18:00</hora>
            <equipos>
                <local>Cardinals</local>
                <visitante>Raiders</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 20 de diciembre</fecha>
            <hora>19:30</hora>
            <equipos>
                <local>Bears</local>
                <visitante>Bengals</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 21 de diciembre</fecha>
            <hora>21:00</hora>
            <equipos>
                <local>Steelers</local>
                <visitante>Chiefs</visitante>
            </equipos>
        </partido>
    </jornada>
    <jornada num="9">
        <partido>
            <fecha>Lunes, 20 de diciembre</fecha>
            <hora>16:30</hora>
            <equipos>
                <local>Cardinals</local>
                <visitante>Bears</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Martes, 21 de diciembre</fecha>
            <hora>18:00</hora>
            <equipos>
                <local>Steelers</local>
                <visitante>Rams</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 22 de diciembre</fecha>
            <hora>19:30</hora>
            <equipos>
                <local>Cowboys</local>
                <visitante>Raiders</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 23 de diciembre</fecha>
            <hora>21:00</hora>
            <equipos>
                <local>Bengals</local>
                <visitante>Chiefs</visitante>
            </equipos>
        </partido>
    </jornada>
    <jornada num="10">
        <partido>
            <fecha>Lunes, 27 de diciembre</fecha>
            <hora>16:30</hora>
            <equipos>
                <local>Bears</local>
                <visitante>Cardinals</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Martes, 28 de diciembre</fecha>
            <hora>18:00</hora>
            <equipos>
                <local>Rams</local>
                <visitante>Steelers</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Miércoles, 29 de diciembre</fecha>
            <hora>19:30</hora>
            <equipos>
                <local>Raiders</local>
                <visitante>Cowboys</visitante>
            </equipos>
        </partido>
        <partido>
            <fecha>Jueves, 30 de diciembre</fecha>
            <hora>21:00</hora>
            <equipos>
                <local>Chiefs</local>
                <visitante>Bengals</visitante>
            </equipos>
        </partido>
    </jornada>      
</temporada1>
