=== Rolk254/nsla/xm_xs/clasi.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="clasificacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="equipo" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nombre"/>
              <xs:element type="xs:byte" name="partidos_jugados"/>
              <xs:element type="xs:byte" name="victorias"/>
              <xs:element type="xs:byte" name="derrotas"/>
              <xs:element type="xs:byte" name="empates"/>
              <xs:element type="xs:string" name="locales"/>
              <xs:element type="xs:string" name="visitantes"/>
              <xs:element type="xs:byte" name="puntos_perdidos"/>
              <xs:element type="xs:byte" name="puntos_concedidos"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Rolk254/nsla/xm_xs/clasi.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="clasi.xsl"?>
<clasificacion xsi:noNamespaceSchemaLocation="clasi.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <equipo>
        <nombre>cardinals</nombre>
        <partidos_jugados>2</partidos_jugados>
        <victorias>1</victorias>
        <derrotas>1</derrotas>
        <empates>0</empates>
        <locales>1-1</locales>
        <visitantes>0-0</visitantes>
        <puntos_perdidos>70</puntos_perdidos>
        <puntos_concedidos>27</puntos_concedidos>
    </equipo>
    <equipo>
        <nombre>Cowboys</nombre>
        <partidos_jugados>2</partidos_jugados>
        <victorias>1</victorias>
        <derrotas>0</derrotas>
        <empates>1</empates>
        <locales>0-0</locales>
        <visitantes>1-0</visitantes>
        <puntos_perdidos>67</puntos_perdidos>
        <puntos_concedidos>33</puntos_concedidos>
    </equipo>
    <equipo>
        <nombre>Raiders</nombre>
        <partidos_jugados>2</partidos_jugados>
        <victorias>0</victorias>
        <derrotas>0</derrotas>
        <empates>2</empates>
        <locales>0-0</locales>
        <visitantes>0-0</visitantes>
        <puntos_perdidos>54</puntos_perdidos>
        <puntos_concedidos>19</puntos_concedidos>
    </equipo>
    <equipo>
        <nombre>Steelers</nombre>
        <partidos_jugados>2</partidos_jugados>
        <victorias>2</victorias>
        <derrotas>0</derrotas>
        <empates>0</empates>
        <locales>1-0</locales>
        <visitantes>1-0</visitantes>
        <puntos_perdidos>50</puntos_perdidos>
        <puntos_concedidos>30</puntos_concedidos>
    </equipo>
    <equipo>
        <nombre>Bengals</nombre>
        <partidos_jugados>2</partidos_jugados>
        <victorias>1</victorias>
        <derrotas>0</derrotas>
        <empates>1</empates>
        <locales>0-0</locales>
        <visitantes>1-0</visitantes>
        <puntos_perdidos>33</puntos_perdidos>
        <puntos_concedidos>66</puntos_concedidos>
    </equipo>
    <equipo>
        <nombre>Rams</nombre>
        <partidos_jugados>2</partidos_jugados>
        <victorias>1</victorias>
        <derrotas>1</derrotas>
        <empates>0</empates>
        <locales>1-0</locales>
        <visitantes>0-1</visitantes>
        <puntos_perdidos>37</puntos_perdidos>
        <puntos_concedidos>32</puntos_concedidos>
    </equipo>
    <equipo>
        <nombre>Chiefs</nombre>
        <partidos_jugados>2</partidos_jugados>
        <victorias>0</victorias>
        <derrotas>1</derrotas>
        <empates>1</empates>
        <locales>0-1</locales>
        <visitantes>0-0</visitantes>
        <puntos_perdidos>54</puntos_perdidos>
        <puntos_concedidos>65</puntos_concedidos>
    </equipo>
    <equipo>
        <nombre>Bears</nombre>
        <partidos_jugados>2</partidos_jugados>
        <victorias>2</victorias>
        <derrotas>0</derrotas>
        <empates>0</empates>
        <locales>2-0</locales>
        <visitantes>0-0</visitantes>
        <puntos_perdidos>68</puntos_perdidos>
        <puntos_concedidos>29</puntos_concedidos>
    </equipo>
</clasificacion>
